In [66]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import matplotlib as mpl

In [67]:
df=pd.read_csv('http://stats.moe.gov.tw/files/detail/103/103_degree.csv')

df['男教師總數']=(df.教授男 + df.副教授男+df.助理教授男+df.講師男+df.其他男)
df['女教師總數']=(df.教授女 + df.副教授女+df.助理教授女+df.講師女+df.其他女)
df['教師總數']=(df.男教師總數 + df.女教師總數)

In [78]:
while True:
    print('insert:<1>博士<2>碩士<3>學士<4>專科<5>指定學校<0>離開')
        
    value_in=input('請輸入欲搜尋類別之代碼:')
        
    if int(value_in)==1:
        print('insert:<1>最多教授最高學歷為博士之學校<2>最少教授最高學歷為博士之學校<0>離開')
            
        value_in_a=input('請輸入欲搜尋類別之代碼:')
            
        if int(value_in_a)==1:
            PHD=df['教師學歷']=='博士'
            L_num=list(df[PHD].教師總數)
            L_name=list(df[PHD].學校名稱)
            
            for i in range(0,len(L_num)):
                if (L_num[i])==max(df[PHD].教師總數):
                    print(L_name[i],'有',max(df[PHD].教師總數),'名教師最高學歷為博士\n')
           
        elif int(value_in_a)==2:
            
            PHD=df['教師學歷']=='博士'
            L_num=list(df[PHD].教師總數)
            L_name=list(df[PHD].學校名稱)
            
            for i in range(0,len(L_num)):
                if (L_num[i])==min(df[PHD].教師總數):
                    print(L_name[i],'有',min(df[PHD].教師總數),'名教師最高學歷為博士\n')
        
        elif int(value_in_a)==0:
            print('結束')
            break
        
        else:
            print('您的輸入無效，請重新輸入\n')
        
#=====================博士======================
    elif int(value_in)==2:
        
        MAS=df['教師學歷']=='碩士'
        L_num=list(df[MAS].教師總數)
        L_name=list(df[MAS].學校名稱)
            
        for i in range(0,len(L_num)):
            if (L_num[i])==max(df[MAS].教師總數):
                print(L_name[i],'有',max(df[MAS].教師總數),'名教師最高學歷為碩士，為最多\n')
           
        
#=====================碩士======================
            
    elif int(value_in)==3:
       
        BOC=df['教師學歷']=='學士'
        L_num=list(df[BOC].教師總數)
        L_name=list(df[BOC].學校名稱)
            
        for i in range(0,len(L_num)):
            if (L_num[i])==max(df[BOC].教師總數):
                print(L_name[i],'有',max(df[BOC].教師總數),'名教師具最高學歷為學士，為最多\n')
           
        
#=====================學士======================
    
    elif int(value_in)==4:
        SP=df['教師學歷']=='專科'
        L_num=list(df[SP].教師總數)
        L_name=list(df[SP].學校名稱)
            
        for i in range(0,len(L_num)):
            if (L_num[i])==max(df[SP].教師總數):
                print(L_name[i],'有',max(df[SP].教師總數),'名教師具最高學歷為專科，為最多\n')
    
    elif int(value_in)==5: 
        print('ex:國立臺灣大學')
        sclname=input('請輸入指定學校名稱:')
        scl_name=list(df['學校名稱'])
        
        label=list()
        
        for i in range(0,len(scl_name)):
            if sclname in scl_name[i]:
                df1=df[i:i+1]
                num=i
                label.append(num)
        
        df1=df[label[0]:label[0]+1]
        
        for i in range(1,len(label)):
            
            df1=pd.concat([df1,df[label[i]:label[i]+1]])
            
        break
    
    elif int(value_in)==0:
        print('結束')
        break
            
    else:
        print('您的輸入無效，請重新輸入\n')

df1
#====================學歷========================

insert:<1>博士<2>碩士<3>學士<4>專科<5>指定學校<0>離開
請輸入欲搜尋類別之代碼:5
ex:國立臺灣大學
請輸入指定學校名稱:聖約翰

,學校代碼,學校名稱,日間∕進修別,教師學歷,教授男,教授女,副教授男,副教授女,助理教授男,助理教授女,講師男,講師女,其他男,其他女,助教男,助教女,縣市名稱,男教師總數,女教師總數,教師總數
337,1044,聖約翰科技大學,日,博士,22,1,69,11,29,19,0,0,0,0,0,0,01 新北市,120,31,151
338,1044,聖約翰科技大學,日,碩士,0,1,8,0,14,1,23,14,5,2,0,0,01 新北市,50,18,68
339,1044,聖約翰科技大學,日,學士,1,0,0,0,0,0,2,0,1,1,0,0,01 新北市,4,1,5
340,1044,聖約翰科技大學,日,其他,0,0,0,0,0,0,0,0,4,1,0,0,01 新北市,4,1,5